export {default as Navbar} from './navbar/navbar.jsx'
export {default as Cart} from './cart/cart.jsx'
export {default as Main} from './main/main.jsx'
export {default as MainHeader} from './mainHeader/mainHeader.jsx'
export {default as Category} from './categories/category.jsx'